### ISSUE TITLE
Include storybook on default template

### ISSUE THREAD

**Issue by gustaYo** [sveltejs/sapper-template#120]
I just integrated storybook successfully with sapper. I think it should be included by default.
what are your thoughts?

I would be happy to make a PR

**Comment by arxpoetica** [comment]
If you wanted to build it on a branch, it could live on a separate branch maybe, but it shouldn't be included as the main template. Sapper is unonpionanted when it comes to other frameworks / systems.

**Comment by Rich-Harris** [comment]
To be fair, the default template does include Cypress, which is certainly an opinion. I'm not a Storybook user so don't have an opinion on whether it'd be good to include or not (it's *possible* that for something as opinionated as Sapper we should even consider building an alternative, I don't know), but the idea of making it easy to see/test/document individual components in a more interactive and visual way absolutely has merit.

@gustaYo Do you have a fork somewhere so we could see it in action?

**Comment by arxpoetica** [comment]
@Rich-Harris https://storybook.js.org/docs/guides/guide-svelte/

**Comment by gustaYo** [comment]
@Rich-Harris https://github.com/gustaYo/sapper-storybook

**Comment by arxpoetica** [comment]
This is really cool and maybe timely...I might use it on a current project...

**Comment by rixo** [comment]
For reference, I've submitted a proposal for a more idiomatic support of Svelte v3 in Storybook. People interested in Svelte support in Storybook might want to chime in there: https://github.com/storybooks/storybook/issues/6653

**Comment by antony** [comment]
I like storybook, and am a storybook user. But it is huge, has good, but incomplete support for Svelte, requires webpack, React, and a bunch of other dependencies, and is generally not a good fit for a Sapper template, whilst being an excellent fit for a styleguide or component library (but external to a project).

Going to close this issue on that basis (and the fact that nearly a year has passed), but happy for it to be re-opened if people feel strongly otherwise.
