### ISSUE TITLE
parcel bundler support

### ISSUE THREAD

**Issue by IsaacHub** [sveltejs/sapper-template#124]
Could someone make available a starter template only using parceljs?

**Comment by Conduitry** [comment]
This would require implementation in Sapper itself, not just the creation of a starter template - and I don't think this will be given much priority. I also don't think any of the core maintainers have much experience at all with Parcel.

Is there a reason for not using the webpack or Rollup starter projects?

**Comment by IsaacHub** [comment]
Because everybody likes the way parcel works. If someone make such template, then thousands of people will be happy.

**Comment by GitGangGuy** [comment]
I know I'm late on the issue, but I'd like to leave a bump. Is there any way I can integrate the parcel bundler with sapper or use rollup to bundle my sapper files?

**Comment by pngwn** [comment]
Sapper is tightly integrated with the bundler, it isn’t just used in the template. Sapper actually has core logic enabling it to work with both rollup and webpack, this would have to be replicated for parcel. 

It is more likely that support for different bundlers would be reduced rather than increased. There is no way to use parcel with sapper and I doubt there will be moving forwards.

**Comment by antony** [comment]
@IsaacHub the point of Parcel is that you just run `npx parcel` in your project directory without any configuration and it builds your app.

Therefore making a starter template is pointless, because it defeats the purpose of parcel.

However, parcel does work with Svelte. @demoorjasper has done a great job of this here https://github.com/DeMoorJasper/parcel-plugin-svelte

**Comment by jthegedus** [comment]
I explored Parcel for Sapper like app a couple years ago. Parcel's svelte plugin does not support:

- `src/routes` files as pages
- SSR + progressive enhancement

I am unsure if Parcel even has the correct compilation lifecycle methods to enable such capabilities. It didn't when I last looked, but haven't checked Parcel v2 yet.

Making Sapper use another bundler like Parcel would be a large amount of work.
