### ISSUE TITLE
blog page not showing

### ISSUE THREAD

**Issue by tomcon** [sveltejs/sapper-template#13]
Not found
Could not GET /blog
home & about links are fine

**Comment by Rich-Harris** [comment]
Man, Windows is a trip. I assumed that using `path.sep` when creating routes was the correct thing to do, but it turns out that `glob` always uses forward slashes, regardless of platform. No idea why.

Also no idea why the tests pass in Appveyor despite this nonsense! I dread to think how many years of productivity have been lost to this sort of thing.

Anyway: 0.2.5 has the fix, if you update `sapper` it should hopefully work!
