### ISSUE TITLE
Can't setup environment

### ISSUE THREAD

**Issue by shashkovdanil** [sveltejs/sapper-template#131]
```sh
npx degit sveltejs/sapper-template#rollup my-app

zsh: no matches found: sveltejs/sapper-template#rollup
```

**Comment by Conduitry** [comment]
Does `#` have a special meaning in your shell? From some quick googling, it sounds like `no matches found` is a zsh error when it's trying to expand something with a wildcard and you need to escape it.

**Comment by vladejs** [comment]
In my case, this is what happens:
```
using cached commit hash 2b845e3728e918530298c0c25404b7a343a172ab
> cloned sveltejs/sapper-template#webpack to sapperv3
```
It gets a cached version of sapper

**Comment by Conduitry** [comment]
I _believe_ we've taken care of quoting the repo and branch all the various references to this.

**Comment by gotys** [comment]
I am too getting the same error as of July 11 / 2019 .. No idea how to get around it - please help

**Comment by Conduitry** [comment]
What are you running, what shell are you using, and what's the exact message it gives you?

**Comment by nojas01** [comment]
getting the same error today (ubuntu 18.10,  Gnome terminal 3.30.1) 
 `
npx degit "sveltejs/sapper-template#rollup" my-app
npx: installed 33 in 6.947s
! could not find commit hash for rollup
`

**Comment by nojas01** [comment]
got the same error. Turns out after the last clean install I didn't install git on this machine. so `sudo apt-get install git ` fixed it for me :man_facepalming:

**Comment by aapeliltd** [comment]
i have the same problem too on window machine. while i was getting the same error (could not commit hash master) on CMD. this is what i did to solve the error.

i type git on the start/search area of the window machine then i select git bash console. then i ran the 
npx degit sveltejs/template my-svelte-project again and it works like charms without issues

i hope this will help someone else using window machine. instead of using default CMD, use Git Bash instead.
