### ISSUE TITLE
How to extend this with tailwind

### ISSUE THREAD

**Issue by brasilikum** [sveltejs/sapper-template#137]
I forked this repo to add support for the latest tailwind beta:
https://github.com/brasilikum/sapper3-tailwind

It works!
Now the bad news: Sapper seems to be getting totally overwhelmed by the many css rules. Rebuilds take upwards 15 seconds.

Given the popularity of tailwind this is likely going to be a question often coming up and I am looking to have it be one of the templates people can use to get started, once I can get it to work fast.

Any ideas how to get this to work faster? Feel free to point me to other projects if sapper itself is likely not the root of the problem

**Comment by dephiros** [comment]
I tried to set things up with rollup but run into a few issues:
- Preprocess takes a long time
- Setting up postcss for non-svelte css breaks the svelte styling for some weird reasons

I ended up switching to webpack(even though i really want to stick with rollup) and ends up with this setup
Feedback is appreciated since I am not great at configuration
https://gist.github.com/dephiros/4d2519de027b60849f0831ede4633fce

**Comment by kevin-DL** [comment]
I made a version trying to get tailwind to work with sapper as well, if you want to take a look.
https://github.com/kevin-DL/sapper-template/tree/webpack-tailwind-now

**Comment by antony** [comment]
This is better discussed [in chat](https://svelte.dev/chat) where we discuss options for creating alternative templates. However the Svelte team are hesitant to bless a particular framework, so I'd suggest that contributing to a community maintained template such as the ones above, and ensuring that it is correctly tagged on github for discoverability purposes would be the best way to address this.
