### ISSUE TITLE
Webpack version does not include babel?

### ISSUE THREAD

**Issue by dephiros** [sveltejs/sapper-template#147]
Hi,

I am trying to use the webpack version to build my site and notice that the default setup does not include babel even though it looks like it is in the package_template file. Does svelte-loader does some babel transformation behind the scene?

If i want to set up jest, is there a way to match the babel version of svelte-loader and jest?

**Comment by Conduitry** [comment]
Babel is mentioned in package_template.json because that file is used to build both the rollup and webpack versions of package.json - but babel is only mentioned in the rollup section, and [does not occur in the built webpack branch](https://github.com/sveltejs/sapper-template/blob/webpack/package.json).

svelte-loader does not have its own version of babel or do any babel transformations. The Sapper feature where it produces two builds - one with Babel transformations and one without - and then chooses which to use in the browser at runtime [is not supported in webpack](https://github.com/sveltejs/sapper/issues/401). So if you want babel transforms, they're going to apply to your (only) build, and you should configure them yourself in webpack.config.js.
