### ISSUE TITLE
client only build process

### ISSUE THREAD

**Issue by etktnse** [sveltejs/sapper-template#156]
I want to build my app and serve it with my own server on a subfolder using a standard file server. But this seems to be failing when I delete the webpack server and service-worker entry points. My local test server is live-server.  And I couldn't find a compile method to just compile client files. I want to use my own existing backend not sapper server.

Also I couldn't see any option to not use a service worker. Service workers are not for everyone and some of us do choose to not have it. ( for example when I'm building an internal page or using it with webviews from an app. ) 

I think sapper should have all the capabilities it has while they are optional and can be disabled.

> Building...
> webpack.config.js must export a { client, server, serviceworker? } object 

WHY? Why I cannot just get a client version that I can use it with whatever server I like

**Comment by antony** [comment]
@etktnse You are using Sapper, which is designed for creating a rich web-application with both a client, and server side.

If you just want to write a client, use [Svelte](https://svelte.dev/) itself instead of Sapper.

If you don't want a service-worker in a Sapper application, just delete it. Note that the `serviceworker` element you have described above is suffixed with a question mark - it is optional.
