### ISSUE TITLE
Gcloud branch

### ISSUE THREAD

**Issue by sanderhahn** [sveltejs/sapper-template#167]
Wanted to add a `#gcloud` branch to the template, which should make deploying to Gcloud Run simpler. Not sure if you want to endorse one cloud provider like that, however it seems logical since it also hosts the Svelte site :) Seems that it is impossible to create a pull request to a non-existing branch, so here is an issue instead. My changes are in: https://github.com/sanderhahn/sapper-template/tree/gcloud

**Comment by antony** [comment]
Thanks for this - because it's something I'd like to start playing with. However, I think that this (since it's basically a readme section and a Dockerfile, neither of which directly relate to Sapper) would be better positioned as a deployment section in the Sapper documentation.

It would be good to have a deployment section there for things like gcloud run, now v2, heroku, netlify, etc.

**Comment by sanderhahn** [comment]
Okay, because the template at the moment seems to recommend `now` which doesn't seem to work the way people expect it to work.

**Comment by antony** [comment]
Yeah - that was for now v1. The section needs a rewrite. I don't think Sapper is likely to work on now v2 properly as it requires bending to a proprietary format which isn't really a goal of the project.

**Comment by sanderhahn** [comment]
Moved into docs at https://github.com/sveltejs/sapper/pull/850 will close this for now...
