### ISSUE TITLE
Cypress throws an exception

### ISSUE THREAD

**Issue by amitport** [sveltejs/sapper-template#177]
running `npm test` with `windows@10.0.18362` `cypress@3.4.1` `node@12.13.0`

I'm getting 
```
    All specs passed!                           00:01        3        3        -        -        -

<my-app-path>\node_modules\cypress\lib\exec\spawn.js:175
          throw err;
          ^

Error: shutdown ENOTCONN
    at ReadStream.Socket._final (net.js:409:25)
    at callFinal (_stream_writable.js:627:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOTCONN',
  code: 'ENOTCONN',
  syscall: 'shutdown'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TODO@0.0.1 cy:run: `cypress run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TODO@0.0.1 cy:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     <my-user-home>\AppData\Roaming\npm-cache\_logs\2019-10-21T13_03_20_571Z-debug.log
ERROR: "cy:run" exited with 1.
npm ERR! Test failed.  See above for more details.
```

**Comment by rdela** [comment]
Did you install Cypress yourself?

Maybe this is a separate issue...but as far as I can tell, Cypress has not been installed in dev dependencies like it should have been since this was https://github.com/sveltejs/template-store if I am reading the tea leaves correctly?

I had to...

```sh
npm i -D cypress
```

...Cypress runs fine, specs pass, like in your log, but no exception. I am on `macOS 10.14.6 (18G1012)` `node v10.16.3` and `cypress@3.5.0`

Links to possible clues I found while investigating missing Cypress dev dependency...
https://github.com/sveltejs/sapper-template/issues/1
https://glebbahmutov.com/blog/testing-svelte-store/
https://github.com/sveltejs/template-store/blob/master/package.json#L5

**Comment by amitport** [comment]
Hi, yes this originates from https://github.com/sveltejs/template-store but I did install Cypress as dev dependency.
(Otherwise no tests would run)

**Comment by rdela** [comment]
Thanks Amit, I guess I will open a separate issue about the missing dev dependency then. If you upgrade to latest `cypress@3.6.0`, are you still having the issue?

**Comment by rdela** [comment]
...turns out there is an old issue about the missing dev dependency: https://github.com/sveltejs/sapper-template/issues/22 

Agree with tomasvts comment at the bottom:

> This should be explained in the docs:
> https://sapper.svelte.dev/docs/#Testing

I will open a PR [over there](https://github.com/sveltejs/sapper/blob/master/site/content/docs/14-testing.md).

**Comment by tetedacier** [comment]
I've created a [new PR](https://github.com/sveltejs/sapper-template/pull/194) targeting the README file to fix this kind of issue for the new comer, what are your feelings about it ?

**Comment by Conduitry** [comment]
We've removed the Cypress integration for a couple of reasons, outlined in #263, so I'm closing this.
