### ISSUE TITLE
Add example on authentication

### ISSUE THREAD

**Issue by vladejs** [sveltejs/sapper-template#37]
How authentication can be achieved? Is there a best practice?

I think the best way is to integrate with ooth.

**Comment by Crisfole** [comment]
Currently under discussion here: https://github.com/sveltejs/sapper/issues/178

**Comment by vladejs** [comment]
I'm reopening this since I haven't found a concrete best practice to authenticate on Sapper > 0.27.1 with Svelte 3.

**Comment by nielsvandermolen** [comment]
Here is a specific example using express-session and the Sapper session store which can be useful for other people struggling with authentication in Sapper.

https://www.nielsvandermolen.com/authentication-example-svelte-sapper/

**Comment by thismatters** [comment]
I think the original question "Is there a best practice?" still is open. The article linked shows a method, but ought that be the _de-facto_ choice for handling auth tokens? 

I would be curious to see an example of using localStorage for a token and/or reasons why localStorage would be a poor choice. Likewise for cookies.

**Comment by Crisfole** [comment]
@thismatters the details of how to store auth tokens are contentious and a matter of personal preference, which is why no best practice is offered. In the case of sapper you almost certainly will want to store a cookie. It's the only way to push back data on every request: this means your initial request that gets SSR and each subsequent request for api level stuff.

But other than that you've got options. I like jwt tokens, you might want to just encrypt the user ID and send it back

**Comment by antony** [comment]
Closing as this will end up on the society site at some point as a Recipe.

Right now you have at least two concrete examples (that are in production use):

https://github.com/antony/sapper-authentication-demo

And an oAuth tutorial

https://enzy.org/blog/integrating-auth0-with-sapper

It's not something that is likely to end up in this template, however.

**Comment by r03** [comment]
Would be nice if there was a simple sapper example with passport and without a separate backend.
