### ISSUE TITLE
Loading svelte components from node_modules

### ISSUE THREAD

**Issue by UnwrittenFun** [sveltejs/sapper-template#61]
Few issues making it difficult to load svelte components from the node_modules folder out of the box.

* Firstly, mainFields is not specified with 'svelte' in it.
* Secondly node_modules is being excluded in the rule to load .html files.

* And lastly, on the server side, this line is preventing webpack from bundling the svelte component and makes it load it as an external module which fails.
https://github.com/sveltejs/sapper-template/blob/280f48f73eefee2995a5b42013565d00d31bb6cd/webpack/server.config.js#L11

**Comment by MaxMilton** [comment]
I've run into this as a blocker too. For the time being, I have to maintain shared components locally for each project but obviously that's undesirable going forward.

**Comment by Rich-Harris** [comment]
I've tweaked the configs (https://github.com/sveltejs/sapper-template/commit/144eb411e16b525bac42cf84745816abd03cdf47) and updated the README with a section on this: https://github.com/sveltejs/sapper-template/blob/master/README.md#using-external-components. Thanks

**Comment by rob-balfre** [comment]
@Rich-Harris the issue we're having here is twofold;  1) we have a component lib (not just the one) we want to import and secondly we want to be able to npm link or "file:component-lib" from package.json so we can work locally on external components. Currently the above solution does't work for us. 

Example of the problem here:
Components:
https://github.com/rob-balfre/sapper-import-external-components-example
 
Sapper:
https://github.com/rob-balfre/sapper-import-external-components-example

**Comment by Conduitry** [comment]
Importing a component lib should just work by having `pkg.svelte` point to a module with multiple named exports of other Svelte components, as described elsewhere. The issues with npm linking should also be fixed now that we're using the `dedupe` option in `rollup-plugin-node-resolve` and the `alias` option in the webpack config.
